version: "3.5"

services:
  zerotier-moon:
    image: zerotier-moon
    container_name: zerotier-moon
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 9993:9993/udp
    command:
      - -p 9993
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data/Docker/ZerotierOne:/var/lib/zerotier-one
